### ISSUE TITLE
Make new join page mobile friendly

### ISSUE THREAD

**Issue by euyterho** [PeoplesMomentum/projects#49]
**As a prospective member
I can become a member of Momentum and pay my membership dues on a mobile device
so that becoming a member is not restricted by a prospective member's access to a computer.**

# Acceptance criteria
- Test if the current join form looks alright and usable on mobile

**Comment by simoneduca** [comment]
Which one is the new join page @euyterho ? This one looks fine on mobile https://join.peoplesmomentum.com/

**Comment by pete-rossetti** [comment]
Yea it does - I think the new one wants to be shorter to join then take you to other questions after joiner has paid
