### ISSUE TITLE
Pick a theme that lets us most quickly style Wordpress according to the design document

### ISSUE THREAD

**Issue by ruthcsberry** [PeoplesMomentum/projects#55]
Idea is to find a wordpress theme that can be easily adapted to match the new design

**Comment by pete-rossetti** [comment]
Installed divi theme a possibility has a built in page builder - from elegant themes https://www.elegantthemes.com/gallery/divi/

Also Genesis Framework has been suggested: https://my.studiopress.com/themes/genesis/

**Comment by astonishemail** [comment]
I use Divi almost exclusively. It is very easy to use and has some excellent responsive features. It is super customizable so you can replicate pretty much anything in it. It's front-end editor is also pretty good too.

**Comment by pete-rossetti** [comment]
Then if the team decide to go with this can you help - r u in Brighton this weekend at all??
 I've used it on a couple of projects

**Comment by pete-rossetti** [comment]
Here is the new design: 
[Momentum Pages.pdf](https://github.com/PeoplesMomentum/projects/files/1321927/Momentum.Pages.pdf)

**Comment by pete-rossetti** [comment]
OK possible to use a blank theme as a boilerplate to start from

**Comment by pete-rossetti** [comment]
Installed blank theme - bare bones - blank canvas

**Comment by pete-rossetti** [comment]
Back to divi and created child theme from which to work from
